# ==============================================================================
# Renovate - Automated Dependency Management Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Automated dependency update management using Renovate Bot. Continuously
# monitors project dependencies across multiple package managers and creates
# pull requests for available updates, security patches, and version upgrades.
# Helps maintain up-to-date dependencies and reduces technical debt.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Multi-language dependency detection (npm, pip, Maven, Go, Docker, etc.)
# - Automated pull request creation for dependency updates
# - Security vulnerability patch detection
# - Configurable versioning strategies (semver, pin, range)
# - Grouping of related updates to reduce PR noise
# - Smart scheduling to avoid disrupting development workflows
# - Supports monorepos and multi-project repositories
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/sca/renovate@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Custom version:
#   - uses: ministryofjustice/devsecops-actions/sca/renovate@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate-version: "42.64.1"
#
# ==============================================================================
# CONFIGURATION
# ==============================================================================
# Renovate behaviour can be customised using renovate.json
# in the repository root. See: https://docs.renovatebot.com/configuration-options/
#
# ==============================================================================
# TOOL INFORMATION
# ==============================================================================
# Tool: Renovate Bot
# GitHub Action: renovatebot/github-action@v44.2.2
# Documentation: https://docs.renovatebot.com/
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Default Renovate Version: 42.64.1
# Last Updated: 2026-01-15
#
# ==============================================================================

name: 🔁 Renovate
description: Renovate scan
author: Ministry of Justice UK

inputs:
  renovate-version:
    required: false
    description: "Renovate CLI version to use for dependency scanning. Specify the version number without the 'v' prefix."
    default: "42.64.1"

  token:
    required: true
    description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."

runs:
  using: composite
  steps:
    - name: Scan
      uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # v44.2.2
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        RENOVATE_MINIMUM_RELEASE_AGE_BEHAVIOUR: "timestamp-required"
        RENOVATE_MINIMUM_RELEASE_AGE: 3
