# ==============================================================================
# Cruft Update Pull Request - Template Synchronization Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Orchestrates the template synchronisation workflow by detecting upstream
# template changes, applying updates, and creating automated pull requests
# with the synchronized modifications. This action runs cruft update to compare
# the current repository state with the upstream template, commits any changes
# with signed commits, and opens a pull request for review and merging.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Automatic template update detection with cruft
# - Non-interactive update application (--skip-apply-ask)
# - Strict mode enforcement for consistency (--strict)
# - Dated branch naming for easy tracking
# - Optional GPG-signed commits
# - HTTPS token-based authentication for pushing changes
# - Automated pull request creation via GitHub API
# - Configurable base branch targeting
# - Customizable commit messages and headings
# - Proper Git configuration and authentication
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/cruft/create@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# With custom base branch:
#   - uses: ministryofjustice/devsecops-actions/cruft/create@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       base-branch: "develop"
#
# ==============================================================================
# PREREQUISITES
# ==============================================================================
# - Repository must contain .cruft.json file
# - Cruft must be installed (via install action)
# - Authentication must be configured (via authenticate action for private templates)
# - GitHub token with pull request write permissions
# - Git must be available in the runner environment
# - For signed commits: GPG signing key must be configured
#
# ==============================================================================
# WORKFLOW PROCESS
# ==============================================================================
# 1. Generate GitHub App token or use provided token for authentication
# 2. Set environment variables for branch and base branch names
# 3. Configure token selection (GitHub App or personal access token)
# 4. Create pull request with template updates using peter-evans/create-pull-request
# 5. Automatically commit changes with signed commits (if configured)
# 6. Apply labels and assign reviewers as specified
# 7. Push changes to new branch and open pull request
#
# ==============================================================================
# BRANCH NAMING CONVENTION
# ==============================================================================
# Format: chore/cookie-cutter-update-YYYYMMDD
# Example: chore/cookie-cutter-update-20260128
#
# This convention:
# - Groups template updates under 'chore' scope
# - Uses date suffix for uniqueness and tracking
# - Follows semantic commit conventions
#
# ==============================================================================
# PULL REQUEST DETAILS
# ==============================================================================
# Title: "chore(update): cruft update"
# Base: Specified base branch (default: main)
# Head: Generated branch name with date
# Body: Automatically generated by GitHub
#
# ==============================================================================
# TOOL INFORMATION
# ==============================================================================
# Tool: Cruft
# Documentation: https://cruft.github.io/cruft/
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Last Updated: 2026-01-30
#
# ==============================================================================

name: ✏️ Create
description: Validates whether the template repository has been updated and creates a new pull request with synchronized changes if updates are available
author: Ministry of Justice UK

inputs:
  base-branch:
    required: false
    default: "main"
    description: "Target base branch where the pull request will be created and merged."

  target-branch-name:
    required: false
    description: "Branch name to use when creating the pull request (supports date expansion)"
    default: "chore/cookie-cutter-update-$(date +%Y%m%d)"

  target-branch-heading:
    required: false
    description: "Pull request title following conventional commit format"
    default: "chore(update): cruft update"

  target-branch-commit-message:
    required: false
    description: "Git commit message for template synchronisation changes"
    default: "chore(update): cruft update"

  target-branch-body:
    required: false
    description: "Pull request body describing template updates and changes"
    default: "chore(update): cruft update"

  target-branch-labels:
    required: false
    description: "Comma or newline-separated list of labels to apply to the pull request"
    default: ""

  target-branch-reviewers:
    required: false
    description: "Comma or newline-separated list of GitHub usernames to request reviews from"
    default: ""

  github-app-id:
    required: false
    description: "GitHub App ID for authentication token generation with workflow permissions"
    default: ""

  github-app-private-key:
    required: false
    description: "GitHub App private key in PEM format for authentication"
    default: ""

  github-app-owner:
    required: false
    description: "GitHub organisation or user name for GitHub App token scope"
    default: ""

  github-app-repositories:
    required: false
    description: "Comma-separated list of repository names for GitHub App token scope"
    default: ""

  token:
    required: false
    description: "GitHub personal access token or GITHUB_TOKEN with contents, pull-requests, and workflow permissions"

runs:
  using: composite
  steps:
    - name: Token
      id: github-app-token-write
      if: inputs.github-app-id != '' && inputs.github-app-private-key != ''
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: "${{ inputs.github-app-id }}"
        private-key: "${{ inputs.github-app-private-key }}"
        owner: "${{ github.repository_owner }}"
        repositories: "${{ github.event.repository.name }}"
        permission-workflows: "write"
        permission-contents: "write"
        permission-pull-requests: "write"

    - name: Variables
      shell: bash
      run: |
        BASE="${{ inputs.base-branch }}"
        BRANCH="${{ inputs.target-branch-name }}"

        echo "BASE=$BASE" >> "$GITHUB_ENV"
        echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

    - name: Configure
      shell: bash
      env:
        APP_TOKEN: ${{ steps.github-app-token-write.outputs.token }}
        INPUT_TOKEN: ${{ inputs.token }}
      run: |
        if [ -n "$APP_TOKEN" ]; then
          echo "TOKEN=$APP_TOKEN" >> "$GITHUB_ENV"
        elif [ -n "$INPUT_TOKEN" ]; then
          TOKEN="$INPUT_TOKEN"
          echo "TOKEN=$INPUT_TOKEN" >> "$GITHUB_ENV"
        else
          echo "Error: No token provided for authentication"
          exit 1
        fi

    - name: PR
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        token: ${{ env.TOKEN }}
        title: "${{ inputs.target-branch-heading }}"
        commit-message: "${{ inputs.target-branch-commit-message }}"
        body: "${{ inputs.target-branch-body }}"
        branch: ${{ env.BRANCH }}
        base: ${{ env.BASE }}
        sign-commits: true
        signoff: true
        labels: "${{ inputs.target-branch-labels }}"
        reviewers: "${{ inputs.target-branch-reviewers }}"
