# ==============================================================================
# TruffleHog - Secret Scanning Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Performs comprehensive secret scanning using TruffleHog to detect exposed
# credentials, API keys, tokens, certificates, and sensitive data across the
# entire repository filesystem. Uses entropy analysis and pattern matching
# to identify high-confidence secrets with minimal false positives.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - 700+ built-in secret detectors for popular services
# - Entropy-based detection for custom secrets
# - Pattern matching with regular expressions
# - High-confidence detection to reduce false positives
# - Scans all files including binary and compressed formats
# - Historical commit scanning capability
# - JSON output for integration and reporting
# - Configurable detection rules and exclusions
#
# ==============================================================================
# DETECTED SECRET TYPES
# ==============================================================================
# Common services detected:
# - Cloud providers: AWS, Azure, GCP
# - Code repositories: GitHub, GitLab, Bitbucket
# - CI/CD: CircleCI, Travis CI, Jenkins
# - Databases: MongoDB, MySQL, PostgreSQL
# - Communication: Slack, Discord, Telegram
# - Payment: Stripe, PayPal, Square
# - And 690+ more services
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage (default settings):
#   - uses: ministryofjustice/devsecops-actions/sca/trufflehog@v1.3.0
#
# With custom configuration:
#   - uses: ministryofjustice/devsecops-actions/sca/trufflehog@v1.3.0
#     with:
#       trufflehog-config-file: ".github/trufflehog-config.yml"
#       trufflehog-output-filename: "sca-trufflehog"
#
# ==============================================================================
# CONFIGURATION
# ==============================================================================
# Custom configuration file format (YAML):
#   detectors:
#     - name: aws
#     - name: github
#   exclude_paths:
#     - "test/**"
#     - "docs/**"
#   verify: true
#
# See: https://github.com/trufflesecurity/trufflehog#configuration
#
# ==============================================================================
# SCAN PARAMETERS
# ==============================================================================
# This action uses the following optimized settings:
# - concurrency: 14 parallel workers
# - no-verification: Skips online secret validation (faster)
# - no-update: Uses pinned detector version
# - fail-on-scan-errors: Ensures scan completion
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# Artifacts generated:
# - sca-trufflehog.json: Complete scan results in JSON format
# - Uploaded to workflow run with 30-day retention
# - Available in "TruffleHog" artifact
#
# ==============================================================================
# BEST PRACTICES
# ==============================================================================
# - Run on all branches and pull requests
# - Use custom config to exclude test fixtures
# - Enable verification for high-risk repositories
# - Integrate with secret rotation workflows
# - Configure alerting for detected secrets
#
# ==============================================================================
# TOOL INFORMATION
# ==============================================================================
# Tool: TruffleHog
# Version: 3.92.4
# Container: trufflesecurity/trufflehog:3.92.4
# Documentation: https://github.com/trufflesecurity/trufflehog
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Last Updated: 2026-02-18
#
# ==============================================================================

name: ðŸ· TruffleHog
description: Entropy-based secret detection
author: Ministry of Justice UK

inputs:
  trufflehog-config-file:
    required: false
    description: "Path to the TruffleHog configuration file for secret scanning customisation. Leave empty to use default settings."
    default: ""

  trufflehog-output-filename:
    required: false
    description: "TruffleHog JSON output file name (`.json` extension will be appended automatically)"
    default: "sca-trufflehog"

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        CONFIG=""

        if [ -n "${{ inputs.trufflehog-config-file }}" ]; then
          CONFIG="--config ${{ inputs.trufflehog-config-file }}"
        fi

        docker run --rm \
        -v "$(pwd)":/src trufflesecurity/trufflehog:3.92.4@sha256:c28ab4a11e01d6fcc10776f65cce015bdf9795f2393cffa2ec0a7c8464ee58b6 \
        filesystem ./ \
        $CONFIG \
        --concurrency=14 \
        --no-verification \
        --no-update \
        --fail-on-scan-errors \
        --json > ${{ inputs.trufflehog-output-filename }}-${{ github.run_number }}${{ github.run_attempt }}${{ strategy.job-index }}.json

    - name: Upload
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: TruffleHog-${{ github.run_number }}${{ github.run_attempt }}${{ strategy.job-index }}
        path: ${{ inputs.trufflehog-output-filename }}-${{ github.run_number }}${{ github.run_attempt }}${{ strategy.job-index }}.json
        retention-days: 30
