# Software Composition Analysis (SCA) Action
# 
# This GitHub Action performs comprehensive software composition analysis including:
# - Dependency review and vulnerability scanning
# - Automated dependency updates via Renovate
# - Secret scanning and security event monitoring
#
# Inputs:
#   renovate: (optional, default: "true")
#     Controls whether Renovate dependency updates should be executed
#
#   renovate-version: (optional, default: "42.64.1")
#     Specifies the version of Renovate CLI to use for dependency updates
#
#   dependency-review-config-file: (optional, default: "")
#     Path to a custom dependency review configuration file relative to repository root
#     If not provided, uses default dependency review settings
#
#   token: (required)
#     GitHub token with the following permissions:
#     - Read/Write: contents, pull requests, issues
#     - Read-only: security events
#
# Usage Example:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: "true"
#       renovate-version: "42.64.1"
#
# Steps:
#   1. Repository checkout - Clones the repository for analysis
#   2. Dependencies - Runs dependency review to identify vulnerabilities
#   3. Renovate - Automatically creates PRs for dependency updates (if enabled)
#
# Environment Variables (Renovate):
#   RENOVATE_AUTODISCOVER: Disabled to prevent automatic repository discovery
#   RENOVATE_REPOSITORIES: Set to current repository only
#

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path relative to your repository."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}

    - name: Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@9d99aa6c5d71d3a20cddbce90e2d8147e589f83e # frozen: v44.2.1
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}
