# Ministry of Justice UK - Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive software composition analysis including:
# - Dependency review and vulnerability scanning
# - Automated dependency updates via Renovate
# - Secret scanning using Trufflehog and devsecops-hooks
# - Code security analysis using CodeQL
#
# Inputs:
#   renovate: (optional, default: "true")
#     Flag to enable/disable Renovate execution for automated dependency updates
#
#   renovate-version: (optional, default: "42.64.1")
#     Specify the Renovate CLI version to use
#
#   dependency-review-config-file: (optional, default: "")
#     Path to custom configuration file for GitHub Actions dependency review
#
#   trufflehog-config-file: (optional, default: "")
#     Path to custom Trufflehog configuration file for secret scanning
#
#   codeql-config-file: (optional, default: "")
#     Path to custom CodeQL configuration file for code analysis
#
#   codeql-upload-findings: (optional, default: "always")
#     Controls when to upload CodeQL findings as SARIF to Code Scanning
#     Set to "never" if default setup is enabled
#
#   token: (required)
#     GitHub repository token with required permissions:
#     - Read/write: contents, pull requests, issues
#     - Read-only: security events
#
# Usage Example:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: "true"
#       codeql-upload-findings: "always"
#
# Outputs:
#   - Dependency review results (inline comments on PR)
#   - Renovate updates (PRs for dependency updates)
#   - Trufflehog scan results (uploaded as artifact)
#   - CodeQL analysis results (uploaded to Code Scanning)

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: 📊 Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}
        head-ref: ${{ github.head_ref || github.sha }}
        base-ref: ${{ github.base_ref || github.event.repository.default_branch }}

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # frozen: v44.2.2
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}

    - name: 🔑 Secrets
      shell: bash
      run: docker run --rm
        \-e GIT_MODE=false
        \-v "$(pwd)":/src
        \ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0 # https://github.com/ministryofjustice/devsecops-hooks

    # Initiate scan
    - name: 🐷 Trufflehog
      shell: bash
      run: |
        CONFIG=""

        if [ -n "${{ inputs.trufflehog-config-file }}" ]; then
          CONFIG="--config ${{ inputs.trufflehog-config-file }}"
        fi

        docker run --rm \
        -v "$(pwd)":/src trufflesecurity/trufflehog:3.92.4@sha256:c28ab4a11e01d6fcc10776f65cce015bdf9795f2393cffa2ec0a7c8464ee58b6 \
        git https://github.com/${{ github.repository }} \
        $CONFIG \
        --concurrency=14 \
        --no-verification \
        --no-update \
        --branch ${{ github.head_ref }} \
        --fail-on-scan-errors \
        --json > trufflehog.json

    # Upload findings
    - name: 🐷 Trufflehog
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # frozen: v6.0.0
      with:
        name: trufflehog
        path: trufflehog.json
        retention-days: 30

      # Sets up CodeQL for analysis
    - name: ⚙️ CodeQL
      uses: github/codeql-action/init@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      with:
        config-file: ${{ inputs.codeql-config-file }}

      # Auto-build for compiled languages
    - name: ⚙️ CodeQL
      uses: github/codeql-action/autobuild@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      continue-on-error: true

    # Finalizes the CodeQL database, runs the analysis, and uploads the results to Code Scanning
    - name: ⚙️ CodeQL
      uses: github/codeql-action/analyze@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      with:
        upload: ${{ inputs.codeql-upload-findings }}
