# Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive security analysis for software dependencies,
# secrets, and vulnerabilities. It orchestrates multiple security scanning tools to ensure
# code quality and security compliance.
#
# Features:
# - Dependency review and management via Renovate
# - OWASP dependency checking
# - Secret scanning with Trufflehog
# - CodeQL static analysis
# - OpenSSF Scorecard security assessment
# - Software Bill of Materials (SBOM) generation
#
# Usage:
#   - name: Run SCA
#     uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: 'true'
#       codeql-upload-findings: 'always'
#
# Required Permissions:
#   - contents: read/write
#   - pull-requests: read/write
#   - issues: read/write
#   - security-events: read
#
# Inputs:
#   renovate:
#     Flag to enable/disable Renovate dependency updates
#     Default: 'true'
#
#   node_version:
#     Node.js runtime version for SBOM generation
#     Default: '24.11.1'
#
#   renovate-version:
#     Renovate CLI version to use
#     Default: '42.64.1'
#
#   dependency-review-config-file:
#     Path to custom dependency review configuration
#     Optional
#
#   trufflehog-config-file:
#     Path to custom Trufflehog configuration
#     Optional
#
#   codeql-config-file:
#     Path to custom CodeQL configuration
#     Optional
#
#   codeql-upload-findings:
#     Controls SARIF upload to Code Scanning ('always' or 'never')
#     Default: 'always'
#
#   docker-images-file:
#     Path to JSON file containing Docker image URIs for SBOM generation
#     Format: {"images": ["ghcr.io/org/image:tag"]}
#     Optional
#
#   token:
#     GitHub token with appropriate permissions
#     Required
#
# Steps:
#   1. Repository checkout and setup
#   2. Dependency review against security advisories
#   3. OWASP dependency vulnerability scanning
#   4. Renovate automated dependency updates (conditional)
#   5. Secret detection in repository
#   6. Trufflehog secret scanning
#   7. CodeQL static code analysis
#   8. OpenSSF Scorecard security assessment
#   9. SBOM generation for dependencies and Docker images

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  node_version:
    required: false
    description: "Node.js version to use"
    default: "24.11.1"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  docker-images-file:
    required: false
    description: "A JSON file an 'images' property as an array containing URIs to docker image, for example 'ghcr.io/ministryofjustice/devsecops-hooks:latest'"
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ./sca/steps/Repository

    - name: 📊 Dependencies
      uses: ./sca/steps/Dependencies
      with:
        dependency-review-config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ./sca/steps/OWASP

    - name: 🔁 Renovate
      if: ${{ inputs.renovate == 'true' }}
      uses: ./sca/steps/Renovate
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ./sca/steps/Secrets

    - name: 🐷 Trufflehog
      uses: ./sca/steps/Trufflehog
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}

    - name: ⚙️ CodeQL
      uses: ./sca/steps/CodeQL
      with:
        codeql-config-file: ${{ inputs.codeql-config-file }}
        codeql-upload-findings: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      uses: ./sca/steps/OpenSSF
      with:
        token: ${{ inputs.token }}

    - name: 📋 SBOM
      uses: ./sca/steps/SBOM
      with:
        token: ${{ inputs.token }}
        node_version: ${{ inputs.node_version }}
        docker-images-file: ${{ inputs.docker-images-file }}
