# ==============================================================================
# Software Composition Analysis (SCA) - Composite GitHub Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Comprehensive software composition analysis (SCA) workflow that orchestrates
# multiple security scanning and dependency management tools. This composite
# action provides enterprise-grade security analysis including dependency
# vulnerability detection, secret scanning, SBOM generation, and compliance
# reporting for GitHub repositories.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Repository checkout with secure token management
# - Dependency review and vulnerability scanning
# - OWASP Dependency-Check for known CVEs
# - Automated dependency updates via Renovate
# - Secret scanning using MOJ custom tools
# - TruffleHog secret detection
# - CodeQL static application security testing (SAST)
# - OpenSSF Scorecard security posture assessment
# - Software Bill of Materials (SBOM) generation
# - Docker image vulnerability scanning
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/sca@3e9745e3fadc4a3ed17e715e86dd017f153a6528
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Advanced usage with custom configuration:
#   - uses: ministryofjustice/devsecops-actions/sca@3e9745e3fadc4a3ed17e715e86dd017f153a6528
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: "true"
#       renovate-version: "42.64.1"
#       node-version: "24.11.1"
#       dependency-review-config-file: ".github/dependency-review-config.yml"
#       trufflehog-config-file: ".github/trufflehog-config.yml"
#       trufflehog-output-filename: "sca-trufflehog"
#       codeql-config-file: ".github/codeql-config.yml"
#       codeql-upload-findings: "always"
#       codeql-languages: "javascript,typescript,python"
#       docker-images-file: "docker-images.json"
#       output-directory-name: "./reports"
#       dependency-check-suppression-file: "dependency-check-suppression.xml"
#
# ==============================================================================
# PREREQUISITES
# ==============================================================================
# - GitHub token with the following permissions:
#   - contents: read/write
#   - pull-requests: read/write
#   - issues: read/write
#   - security-events: read
# - Repository must have GitHub Advanced Security enabled for CodeQL
# - Docker must be available in the runner environment
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# This action generates the following artifacts:
# - SARIF files uploaded to GitHub Code Scanning (OWASP, CodeQL)
# - SBOM artifacts in CycloneDX JSON format:
#   - sca-sbom-repository-{run_number}-{run_attempt}-{job_index}.cdx.json
#   - sca-sbom-*.cdx.json (for Docker images, if configured)
#   - Uploaded as "SBOM-{run_number}{run_attempt}{job_index}" artifact
# - TruffleHog scan results:
#   - {trufflehog-output-filename}-{run_number}{run_attempt}{job_index}.json
#   - Uploaded as "TruffleHog-{run_number}{run_attempt}{job_index}" artifact
#   - 30-day retention
# - OpenSSF Scorecard results:
#   - sca-scorecard.json
#   - Displayed in GitHub job summary
# - OWASP Dependency-Check reports in reports directory:
#   - dependency-check-report.sarif (uploaded to Code Scanning)
#   - dependency-check-report.json
#
# Default output directory: ./reports
# Customisable via output-directory-name input parameter
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Minimum GitHub Enterprise Server: 3.8
# Last Updated: 2026-02-18
#
# ==============================================================================

name: Ministry of Justice UK - SCA ⚡️
description: Software Composition Analysis for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  token:
    required: true
    description: "GitHub repository token with read/write permissions for contents, pull requests, and issues, plus read-only access to security events"

  renovate:
    required: false
    description: "Enable or disable Renovate bot for automated dependency updates"
    default: "true"

  node-version:
    required: false
    description: "Node.js version to use for SBOM generation and related tooling"
    default: "24.11.1"

  renovate-version:
    required: false
    description: "Renovate CLI version to use for dependency scanning (specify without 'v' prefix)"
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "Path to custom dependency review configuration file for GitHub Actions dependency scanning"
    default: ""

  trufflehog-config-file:
    required: false
    description: "Path to custom TruffleHog configuration file for secret scanning customisation"
    default: ""

  trufflehog-output-filename:
    required: false
    description: "TruffleHog JSON output file name (`.json` extension will be appended automatically)"
    default: "sca-trufflehog"

  codeql-config-file:
    required: false
    description: "Path to custom CodeQL configuration file for SAST query customisation"
    default: ""

  codeql-upload-findings:
    required: false
    description: "Control SARIF upload to Code Scanning. Set to 'never' if GitHub's default CodeQL setup is enabled"
    default: "always"

  docker-images-file:
    required: false
    description: "Path to JSON file containing 'images' array with Docker image URIs for container SBOM generation (e.g., 'ghcr.io/ministryofjustice/devsecops-hooks:latest')"
    default: ""

  output-directory-name:
    required: false
    description: "Output directory path for generated reports and scan results"
    default: "reports"

  codeql-languages:
    required: false
    description: "A comma-separated list of CodeQL languages to analyse"

  dependency-check-suppression-file:
    required: false
    description: "The file paths to the suppression XML files"
    default: ""

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ministryofjustice/devsecops-actions/sca/repository@3e9745e3fadc4a3ed17e715e86dd017f153a6528

    - name: 📊 Dependencies
      uses: ministryofjustice/devsecops-actions/sca/dependencies@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        dependency-review-config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ministryofjustice/devsecops-actions/sca/owasp@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        output-directory-name: ${{ inputs.output-directory-name }}
        dependency-check-suppression-file: ${{ inputs.dependency-check-suppression-file }}

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: ministryofjustice/devsecops-actions/sca/renovate@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ministryofjustice/devsecops-actions/sca/moj@3e9745e3fadc4a3ed17e715e86dd017f153a6528

    - name: 🐷 TruffleHog
      uses: ministryofjustice/devsecops-actions/sca/trufflehog@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}
        trufflehog-output-filename: ${{ inputs.trufflehog-output-filename }}

    - name: ⚙️ CodeQL
      uses: ministryofjustice/devsecops-actions/sca/codeql@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        codeql-languages: ${{ inputs.codeql-languages }}
        codeql-config-file: ${{ inputs.codeql-config-file }}
        codeql-upload-findings: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      uses: ministryofjustice/devsecops-actions/sca/ossf@3e9745e3fadc4a3ed17e715e86dd017f153a6528

    - name: 📋 SBOM
      uses: ministryofjustice/devsecops-actions/sca/sbom@3e9745e3fadc4a3ed17e715e86dd017f153a6528
      with:
        node-version: ${{ inputs.node-version }}
        docker-images-file: ${{ inputs.docker-images-file }}
