# Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive security and dependency analysis for repositories,
# including dependency scanning, secret detection, vulnerability assessment, and security scoring.
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       score: 'true'
#       renovate: 'true'
#
# Inputs:
#   score: (optional, default: 'true')
#     Enable/disable OpenSSF Scorecard security checks
#
#   renovate: (optional, default: 'true')
#     Enable/disable Renovate dependency update evaluation
#
#   renovate-version: (optional, default: '42.64.1')
#     Specify the Renovate CLI version to use
#
#   dependency-review-config-file: (optional, default: '')
#     Path to custom dependency review configuration file
#
#   trufflehog-config-file: (optional, default: '')
#     Path to custom Trufflehog configuration file for secret scanning
#
#   codeql-config-file: (optional, default: '')
#     Path to custom CodeQL configuration file
#
#   codeql-upload-findings: (optional, default: 'always')
#     Control SARIF upload to Code Scanning ('always', 'never', or conditions)
#     Set to 'never' if CodeQL default setup is already enabled
#
#   token: (required)
#     GitHub token with the following permissions:
#       - contents: read/write
#       - pull_requests: read/write
#       - issues: read/write
#       - security_events: read
#
# Steps Executed:
#   1. Repository checkout and setup
#   2. Dependency review and vulnerability scanning
#   3. OWASP dependency checking
#   4. Renovate dependency update analysis (conditional)
#   5. GitHub secret scanning
#   6. Trufflehog secret detection
#   7. CodeQL code analysis
#   8. OpenSSF Scorecard security scoring (conditional)
#
# Requirements:
#   - GitHub repository with appropriate permissions
#   - Valid GitHub token with required scopes
#   - Composite actions must be available in ./sca/steps/ directory

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  score:
    required: false
    description: "Flag to execute OSSF checks"
    default: "true"

  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ./sca/steps/Repository

    - name: 📊 Dependencies
      uses: ./sca/steps/Dependencies
      with:
        config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ./sca/steps/OWASP

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: ./sca/steps/Renovate
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ./sca/steps/Secrets

    - name: 🐷 Trufflehog
      uses: ./sca/steps/Trufflehog
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}

    - name: ⚙️ CodeQL
      uses: ./sca/steps/CodeQL
      with:
        config-file: ${{ inputs.codeql-config-file }}
        upload: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      if: inputs.score == 'true'
      uses: ./sca/steps/OpenSSF
      with:
        token: ${{ inputs.token }}
