# Ministry of Justice UK - Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive software composition analysis including:
# - Dependency review and vulnerability scanning
# - Automated dependency updates via Renovate
# - Secret scanning using DevSecOps hooks
# - CodeQL security analysis for multiple languages
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: 'true'
#       renovate-version: '42.64.1'
#       dependency-review-config-file: '.github/dependency-review-config.yml'
#       codeql-config-file: '.github/codeql-config.yml'
#       codeql-upload-findings: 'always'
#
# Inputs:
#   renovate: (optional) Enable/disable Renovate execution. Default: 'true'
#   renovate-version: (optional) Renovate CLI version. Default: '42.64.1'
#   dependency-review-config-file: (optional) Path to dependency review config
#   codeql-config-file: (optional) Path to CodeQL configuration file
#   codeql-upload-findings: (optional) Upload CodeQL SARIF results. Default: 'always'
#   token: (required) GitHub token with permissions for contents, PR, issues (read/write) and security events (read)
#
# Workflow Steps:
#   1. Repository Checkout - Clones the repository for analysis
#   2. Dependencies - Reviews dependencies for vulnerabilities and license compliance
#   3. Renovate - Automates dependency updates (if enabled)
#   4. Secrets - Scans for exposed secrets and credentials
#   5. CodeQL - Initializes, builds, and analyzes code for security vulnerabilities
#
# Required Permissions:
#   contents: read/write
#   pull-requests: read/write
#   issues: read/write
#   security-events: read
#
# Note: Set codeql-upload-findings to 'never' if CodeQL default setup is already enabled

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: 📊 Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}
        head-ref: ${{ github.head_ref || github.sha }}
        base-ref: ${{ github.base_ref || github.event.repository.default_branch }}

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # frozen: v44.2.2
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}

    - name: 🔑 Secrets
      shell: bash
      run: docker run --rm
        \-e GIT_MODE=false
        \-v $(pwd):/src
        \ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0 # https://github.com/ministryofjustice/devsecops-hooks

      # Sets up CodeQL for analysis
    - name: ⚙️ CodeQL
      uses: github/codeql-action/init@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      with:
        config-file: ${{ inputs.codeql-config-file }}

      # Auto-build for compiled languages
    - name: ⚙️ CodeQL
      uses: github/codeql-action/autobuild@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      continue-on-error: true

    # Finalizes the CodeQL database, runs the analysis, and uploads the results to Code Scanning
    - name: ⚙️ CodeQL
      uses: github/codeql-action/analyze@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # frozen: v4.31.9
      with:
        upload: ${{ inputs.codeql-upload-findings }}
