# ==============================================================================
# Software Composition Analysis (SCA) - Composite GitHub Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Comprehensive software composition analysis (SCA) workflow that orchestrates
# multiple security scanning and dependency management tools. This composite
# action provides enterprise-grade security analysis including dependency
# vulnerability detection, secret scanning, SBOM generation, and compliance
# reporting for GitHub repositories.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Repository checkout with secure token management
# - Dependency review and vulnerability scanning
# - OWASP Dependency-Check for known CVEs
# - Automated dependency updates via Renovate
# - Secret scanning using MOJ custom tools
# - TruffleHog secret detection
# - CodeQL static application security testing (SAST)
# - OpenSSF Scorecard security posture assessment
# - Software Bill of Materials (SBOM) generation
# - Docker image vulnerability scanning
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Advanced usage with custom configuration:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: "true"
#       node-version: "24.11.1"
#       codeql-config-file: ".github/codeql-config.yml"
#       docker-images-file: "docker-images.json"
#
# ==============================================================================
# PREREQUISITES
# ==============================================================================
# - GitHub token with the following permissions:
#   - contents: read/write
#   - pull-requests: read/write
#   - issues: read/write
#   - security-events: read
# - Repository must have GitHub Advanced Security enabled for CodeQL
# - Docker must be available in the runner environment
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# This action generates the following artifacts:
# - SARIF files uploaded to GitHub Code Scanning
# - SBOM artifacts in CycloneDX JSON format
# - TruffleHog scan results (JSON)
# - OpenSSF Scorecard results (displayed in job summary)
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Minimum GitHub Enterprise Server: 3.8
# Last Updated: 2026-01-15
#
# ==============================================================================

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  node-version:
    required: false
    description: "Node.js version to use"
    default: "24.11.1"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  docker-images-file:
    required: false
    description: "A JSON file an 'images' property as an array containing URIs to docker image, for example 'ghcr.io/ministryofjustice/devsecops-hooks:latest'"
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ministryofjustice/devsecops-actions/sca/repository@9babea875cafae0e3b05a5ec5aca76d6b560c42e

    - name: 📊 Dependencies
      uses: ministryofjustice/devsecops-actions/sca/dependencies@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        dependency-review-config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ministryofjustice/devsecops-actions/sca/owasp@9babea875cafae0e3b05a5ec5aca76d6b560c42e

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: ministryofjustice/devsecops-actions/sca/renovate@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ministryofjustice/devsecops-actions/sca/moj@9babea875cafae0e3b05a5ec5aca76d6b560c42e

    - name: 🐷 Trufflehog
      uses: ministryofjustice/devsecops-actions/sca/trufflehog@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}

    - name: ⚙️ CodeQL
      uses: ministryofjustice/devsecops-actions/sca/codeql@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        codeql-config-file: ${{ inputs.codeql-config-file }}
        codeql-upload-findings: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      uses: ministryofjustice/devsecops-actions/sca/ossf@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        token: ${{ inputs.token }}

    - name: 📋 SBOM
      uses: ministryofjustice/devsecops-actions/sca/sbom@9babea875cafae0e3b05a5ec5aca76d6b560c42e
      with:
        token: ${{ inputs.token }}
        node-version: ${{ inputs.node-version }}
        docker-images-file: ${{ inputs.docker-images-file }}
