# Ministry of Justice UK - Software Composition Analysis (SCA) Action
#
# This composite GitHub Action performs comprehensive software composition analysis including:
# - Dependency review and vulnerability scanning
# - Automated dependency updates via Renovate
# - Secret scanning using MoJ DevSecOps hooks
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: 'true'
#       renovate-version: '42.64.1'
#       dependency-review-config-file: '.github/dependency-review-config.yml'
#
# Inputs:
#   renovate: (optional) Enable/disable Renovate execution. Default: 'true'
#   renovate-version: (optional) Specific Renovate CLI version to use. Default: '42.64.1'
#   dependency-review-config-file: (optional) Path to custom dependency review config. Default: ''
#   token: (required) GitHub token with permissions:
#     - contents: read/write
#     - pull_requests: read/write
#     - issues: read/write
#     - security_events: read
#
# Steps:
#   1. Checkout repository code
#   2. Run dependency review action to analyze dependencies for vulnerabilities
#   3. Execute Renovate bot for automated dependency updates (if enabled)
#   4. Scan for secrets using MoJ DevSecOps hooks container
#
# Requirements:
#   - Runner must support Docker for secret scanning step
#   - Token must have appropriate repository permissions
#
# Example with minimal configuration:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path relative to your repository."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: 📊 Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}
        head-ref: ${{ github.head_ref || github.sha }}
        base-ref: ${{ github.base_ref || github.event.repository.default_branch }}

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # frozen: v44.2.2
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
      env:
        RENOVATE_AUTODISCOVER: "false"
        RENOVATE_REPOSITORIES: ${{ github.repository }}

    - name: 🔑 Secrets
      shell: bash
      run: docker run --rm
        \-e GIT_MODE=false
        \-v $(pwd):/src
        \ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0 # https://github.com/ministryofjustice/devsecops-hooks
