name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action focuses on dependencies, secret scanning and vulnerabilities management
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path relative to your repository."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # frozen: v6.0.1

    - name: Dependencies
      uses: actions/dependency-review-action@774d14bf50b7a2e2460f9f49e25c52503ecab125 # frozen: v4.8.3
      with:
        config-file: ${{ inputs.dependency-review-config-file }}

    - name: Renovate
      if: inputs.renovate == 'true'
      uses: renovatebot/github-action@f7fad228a053c69a98e24f8e4f6cf40db8f61e08 # frozen: v44.2.1
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}
