# Software Composition Analysis (SCA) GitHub Action
#
# This composite action performs comprehensive security analysis on repositories including:
# - Dependency management and review
# - OWASP security scanning
# - Automated dependency updates via Renovate
# - Secret scanning with multiple tools
# - Code security analysis with CodeQL
# - OpenSSF Scorecard evaluation
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       renovate: 'true'
#       renovate-version: '42.64.1'
#       dependency-review-config-file: '.github/dependency-review-config.yml'
#       trufflehog-config-file: '.github/trufflehog-config.yml'
#       codeql-config-file: '.github/codeql-config.yml'
#       codeql-upload-findings: 'always'
#
# Inputs:
#   renovate: Enable/disable Renovate execution (default: 'true')
#   renovate-version: Renovate CLI version to use (default: '42.64.1')
#   dependency-review-config-file: Path to dependency review configuration
#   trufflehog-config-file: Path to Trufflehog configuration
#   codeql-config-file: Path to CodeQL configuration
#   codeql-upload-findings: When to upload SARIF results (default: 'always', use 'never' if default setup enabled)
#   token: GitHub token with required permissions (required)
#
# Required Token Permissions:
#   - contents: read/write
#   - pull-requests: read/write
#   - issues: read/write
#   - security-events: read
#
# Steps Executed:
#   1. Repository checkout
#   2. Dependency review and analysis
#   3. OWASP dependency check
#   4. Renovate automated updates (conditional)
#   5. GitHub secret scanning
#   6. Trufflehog secret detection
#   7. CodeQL security analysis
#   8. OpenSSF Scorecard evaluation

name: Ministry of Justice UK - SCA ⚡️
description: Software composition analysis GitHub action for dependency management, secret scanning, and security vulnerability detection
author: Ministry of Justice UK

inputs:
  renovate:
    required: false
    description: "Flag to evaluation Renovate execution"
    default: "true"

  renovate-version:
    required: false
    description: "Renovate CLI version, an optional argument which defaults to v42.64.1."
    default: "42.64.1"

  dependency-review-config-file:
    required: false
    description: "GitHub Actions dependency review configuration file path."
    default: ""

  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  codeql-config-file:
    required: false
    description: "CodeQL configuration file path."
    default: ""

  codeql-upload-findings:
    required: false
    description: "Upload the findings from CodeQL as SARIF file to Code Scanning, set to never if default setup is enabled."
    default: "always"

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ./sca/steps/Repository

    - name: 📊 Dependencies
      uses: ./sca/steps/Dependencies
      with:
        dependency-review-config-file: ${{ inputs.dependency-review-config-file }}

    - name: 🔎 OWASP
      uses: ./sca/steps/OWASP

    - name: 🔁 Renovate
      if: inputs.renovate == 'true'
      uses: ./sca/steps/Renovate
      with:
        token: ${{ inputs.token }}
        renovate-version: ${{ inputs.renovate-version }}

    - name: 🔑 Secrets
      uses: ./sca/steps/Secrets

    - name: 🐷 Trufflehog
      uses: ./sca/steps/Trufflehog
      with:
        trufflehog-config-file: ${{ inputs.trufflehog-config-file }}

    - name: ⚙️ CodeQL
      uses: ./sca/steps/CodeQL
      with:
        codeql-config-file: ${{ inputs.codeql-config-file }}
        codeql-upload-findings: ${{ inputs.codeql-upload-findings }}

    - name: 🛡 OpenSSF
      uses: ./sca/steps/OpenSSF
      with:
        token: ${{ inputs.token }}
