# ==============================================================================
# GitHub Repository Archive Check - Composite Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Automated repository health monitoring action that scans GitHub repository
# commit history to identify dormant repositories eligible for archival. Analyses
# repository activity patterns and dispatches email notifications when
# repositories have been inactive for a specified period, helping organisations
# maintain clean repository portfolios and proactive governance workflows.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Automated commit history analysis
# - Configurable inactivity thresholds
# - GOV.UK Notify email integration
# - Non-destructive read-only scanning
# - Comprehensive activity reporting
# - Date-based eligibility detection
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/github/repository/archive@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       notification-email: "team@example.gov.uk"
#       gov-notify-key: ${{ secrets.GOV_NOTIFY_API_KEY }}
#       gov-notify-template-id: ${{ secrets.GOV_NOTIFY_TEMPLATE_ID }}
#
# Advanced usage with custom threshold:
#   - uses: ministryofjustice/devsecops-actions/github/repository/archive@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       archival-days: "180"
#       notification-email: "governance@example.gov.uk"
#       gov-notify-key: ${{ secrets.GOV_NOTIFY_API_KEY }}
#       gov-notify-template-id: ${{ secrets.GOV_NOTIFY_TEMPLATE_ID }}
#
# ==============================================================================
# PREREQUISITES
# ==============================================================================
# - GitHub token with the following permissions:
#   - contents: read
# - GOV.UK Notify account with API key
# - GOV.UK Notify email template configured
# - Repository with commit history
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# This action generates the following:
# - Email notification via GOV.UK Notify (if repository exceeds threshold)
# - Console logs with repository activity status
# - Exit status indicating archival eligibility
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Minimum GitHub Enterprise Server: 3.8
# Last Updated: 2026-02-10
#
# ==============================================================================

name: Ministry of Justice UK - GitHub - Archive check 🔎
description: Scan GitHub repository commit history to determine if repository is due for archival, then dispatch an alert email to the provided email address.
author: Ministry of Justice UK

inputs:
  archival-days:
    required: false
    description: "Number of non-activity days in a repository"
    default: "90"

  notification-email:
    required: true
    description: "Notification email address to dispatch an email for the repository which has been dormant for 'archival-days' and therefore eligible for archival"

  gov-notify-key:
    required: true
    description: "GovNotify API key"

  gov-notify-template-id:
    required: true
    description: "GovNotify template ID"

  node-version:
    required: false
    description: "Node.js version to use"
    default: "24.11.1"

  token:
    required: true
    description: "GitHub token with read-only access to repository contents (for example, contents: read)."

runs:
  using: composite
  steps:
    - name: 📦 Repository
      uses: ministryofjustice/devsecops-actions/sca/repository@9babea875cafae0e3b05a5ec5aca76d6b560c42e

    - name: ⚡️ Node
      uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5 # v6.1.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: ⚙️ Execute
      shell: bash
      working-directory: ${{ github.workspace }}
      run: node ${{ github.action_path }}/../../../dist/index.js --github --archive --days "${{ inputs.archival-days }}" --email "${{ inputs.notification-email }}" --key "${{ inputs.gov-notify-key }}" --template-id "${{ inputs.gov-notify-template-id }}" --repository-name "${{ github.repository }}"
