# Trufflehog Secret Scanning Action
#
# This composite action performs secret scanning using Trufflehog to detect
# exposed credentials and sensitive information in git repositories.
#
# Inputs:
#   trufflehog-config-file:
#     description: Optional path to a Trufflehog configuration file for customizing scan behavior
#     required: false
#     default: ""
#     type: string
#
#   token:
#     description: GitHub Personal Access Token or repository token with the following permissions:
#                  - contents: read/write
#                  - pull_requests: read/write
#                  - issues: read/write
#                  - security_events: read
#     required: true
#     type: string
#
# Workflow Steps:
#   1. Scan: Executes Trufflehog Docker container to scan the repository
#      - Uses pinned version 3.92.4 with SHA256 verification
#      - Scans the current branch or default branch
#      - Outputs results to sca-trufflehog.json
#      - Runs with 14 concurrent workers
#      - Fails on scan errors
#
#   2. Upload: Uploads scan results as an artifact
#      - Always runs regardless of scan outcome
#      - Retains artifact for 30 days
#      - Named "ðŸ· TruffleHog"
#
# Example Usage:
#   - uses: ministryofjustice/devsecops-actions/sca/steps/Trufflehog@main
#     with:
#       trufflehog-config-file: .trufflehog.yml
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Security Notes:
#   - Docker image is pinned to specific SHA256 digest for supply chain security
#   - Verification is disabled (--no-verification flag)
#   - Auto-updates are disabled (--no-update flag)

name: ðŸ· Trufflehog
description: Trufflehog scan
author: Ministry of Justice UK

inputs:
  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: |
        CONFIG=""

        if [ -n "${{ inputs.trufflehog-config-file }}" ]; then
          CONFIG="--config ${{ inputs.trufflehog-config-file }}"
        fi

        docker run --rm \
        -v "$(pwd)":/src trufflesecurity/trufflehog:3.92.4@sha256:c28ab4a11e01d6fcc10776f65cce015bdf9795f2393cffa2ec0a7c8464ee58b6 \
        git https://github.com/${{ github.repository }} \
        $CONFIG \
        --concurrency=14 \
        --no-verification \
        --no-update \
        --branch ${{ github.head_ref || github.event.repository.default_branch }} \
        --fail-on-scan-errors \
        --json > sca-trufflehog.json

    - name: Upload
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: TruffleHog
        path: sca-trufflehog.json
        retention-days: 30
