# GitHub Action for running Trufflehog secret scanning on a repository
#
# This action performs the following steps:
# 1. Runs Trufflehog scanner using Docker to detect secrets in the filesystem
# 2. Uploads the scan results as an artifact
#
# Inputs:
#   trufflehog-config-file: (optional) Path to a custom Trufflehog configuration file
#   token: (required) GitHub token with appropriate permissions (read/write to contents,
#          pull requests, issues; read-only to security events)
#
# The scan:
# - Uses Trufflehog version 3.92.4 (pinned with SHA256 digest)
# - Scans the entire filesystem of the repository
# - Runs with 14 concurrent workers
# - Disables verification and updates
# - Fails on scan errors
# - Outputs results in JSON format to sca-trufflehog.json
#
# Artifacts:
# - Name: TruffleHog
# - File: sca-trufflehog.json
# - Retention: 30 days
# - Upload occurs regardless of scan success/failure (if: always())
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca/steps/Trufflehog@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       trufflehog-config-file: .trufflehog.yml  # optional

name: ðŸ· Trufflehog
description: Trufflehog scan
author: Ministry of Justice UK

inputs:
  trufflehog-config-file:
    required: false
    description: "Trufflehog configuration file path."
    default: ""

  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: |
        CONFIG=""

        if [ -n "${{ inputs.trufflehog-config-file }}" ]; then
          CONFIG="--config ${{ inputs.trufflehog-config-file }}"
        fi

        docker run --rm \
        -v "$(pwd)":/src trufflesecurity/trufflehog:3.92.4@sha256:c28ab4a11e01d6fcc10776f65cce015bdf9795f2393cffa2ec0a7c8464ee58b6 \
        filesystem ./ \
        $CONFIG \
        --concurrency=14 \
        --no-verification \
        --no-update \
        --fail-on-scan-errors \
        --json > sca-trufflehog.json

    - name: Upload
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: TruffleHog
        path: sca-trufflehog.json
        retention-days: 30
