# ==============================================================================
# OWASP Dependency-Check - Vulnerability Scanning Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Performs comprehensive dependency vulnerability scanning using OWASP
# Dependency-Check. Identifies known security vulnerabilities (CVEs) in
# project dependencies by comparing against the National Vulnerability
# Database (NVD) and other vulnerability databases. Generates SARIF reports
# for integration with GitHub Code Scanning.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Scans dependencies for known CVEs (Common Vulnerabilities and Exposures)
# - Supports multiple languages: Java, .NET, JavaScript, Python, Ruby, and more
# - Generates SARIF format reports for GitHub Code Scanning integration
# - Configurable CVSS threshold (default: 7 - High severity)
# - Automatically uploads findings to GitHub Security tab
# - Provides detailed vulnerability information with remediation guidance
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/sca/owasp@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# With custom output directory:
#   - uses: ministryofjustice/devsecops-actions/sca/owasp@v1.3.0
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#       output-directory-name: "reports"
#
# ==============================================================================
# SEVERITY THRESHOLDS
# ==============================================================================
# CVSS Score Scale:
# - 0.0: None
# - 0.1-3.9: Low
# - 4.0-6.9: Medium
# - 7.0-8.9: High
# - 9.0-10.0: Critical
#
# This action fails on CVSS >= 7.0 (High/Critical vulnerabilities)
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# - SARIF report: ./reports/dependency-check-report.sarif
# - Uploaded to GitHub Code Scanning (Security tab)
# - JSON report: ./reports/dependency-check-report.json
#
# ==============================================================================
# TOOL INFORMATION
# ==============================================================================
# Tool: OWASP Dependency-Check
# Version: 1.1.0 (GitHub Action)
# Documentation: https://owasp.org/www-project-dependency-check/
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Last Updated: 2026-02-18
#
# ==============================================================================

name: 🔎 OWASP
description: Dependency vulnerability scanning
author: Ministry of Justice UK

inputs:
  output-directory-name:
    required: false
    description: "Output directory path for generated reports and scan results"
    default: "reports"

  dependency-check-suppression-file:
    required: false
    description: "The file paths to the suppression XML files"
    default: ""

runs:
  using: composite
  steps:
    - name: Scan
      uses: dependency-check/Dependency-Check_Action@1e54355a8b4c8abaa8cc7d0b70aa655a3bb15a6c # v1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: ${{ github.repository }}
        format: "SARIF"
        path: "."
        out: ${{ inputs.output-directory-name }}
        args: >
          --failOnCVSS 7
          --prettyPrint
          --format SARIF
          ${{ inputs.dependency-check-suppression-file && format('--suppression "{0}"', inputs.dependency-check-suppression-file) || '' }}

    - name: Upload
      if: always()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: ./${{ inputs.output-directory-name }}/dependency-check-report.sarif
