# ==============================================================================
# OWASP Dependency-Check - Vulnerability Scanning Action
# ==============================================================================
#
# Copyright (c) Ministry of Justice UK
# SPDX-License-Identifier: MIT
#
# ==============================================================================
# DESCRIPTION
# ==============================================================================
# Performs comprehensive dependency vulnerability scanning using OWASP
# Dependency-Check. Identifies known security vulnerabilities (CVEs) in
# project dependencies by comparing against the National Vulnerability
# Database (NVD) and other vulnerability databases. Generates SARIF reports
# for integration with GitHub Code Scanning.
#
# ==============================================================================
# FEATURES
# ==============================================================================
# - Scans dependencies for known CVEs (Common Vulnerabilities and Exposures)
# - Supports multiple languages: Java, .NET, JavaScript, Python, Ruby, and more
# - Generates SARIF format reports for GitHub Code Scanning integration
# - Configurable CVSS threshold (default: 7 - High severity)
# - Automatically uploads findings to GitHub Security tab
# - Provides detailed vulnerability information with remediation guidance
#
# ==============================================================================
# USAGE
# ==============================================================================
# Basic usage:
#   - uses: ministryofjustice/devsecops-actions/sca/owasp@main
#
# ==============================================================================
# SEVERITY THRESHOLDS
# ==============================================================================
# CVSS Score Scale:
# - 0.0: None
# - 0.1-3.9: Low
# - 4.0-6.9: Medium
# - 7.0-8.9: High
# - 9.0-10.0: Critical
#
# This action fails on CVSS >= 7.0 (High/Critical vulnerabilities)
#
# ==============================================================================
# OUTPUTS
# ==============================================================================
# - SARIF report: ./reports/dependency-check-report.sarif
# - Uploaded to GitHub Code Scanning (Security tab)
# - JSON report: ./reports/dependency-check-report.json
#
# ==============================================================================
# TOOL INFORMATION
# ==============================================================================
# Tool: OWASP Dependency-Check
# Version: 1.1.0 (GitHub Action)
# Documentation: https://owasp.org/www-project-dependency-check/
#
# ==============================================================================
# VERSION INFORMATION
# ==============================================================================
# Action Version: 1.0.0
# Last Updated: 2026-01-15
#
# ==============================================================================

name: 🔎 OWASP
description: OWASP dependency scan
author: Ministry of Justice UK

inputs:
  token:
    required: true
    description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."

runs:
  using: composite
  steps:
    - name: Scan
      uses: dependency-check/Dependency-Check_Action@1e54355a8b4c8abaa8cc7d0b70aa655a3bb15a6c # v1.1.0
      with:
        project: ${{ github.repository }}
        path: "."
        format: JSON
        args: >
          --failOnCVSS 7
          --prettyPrint
          --format SARIF
          --out ./reports

    - name: Upload
      if: always()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: ./reports/dependency-check-report.sarif
