# Composite action for scanning secrets, credentials, and tokens in the codebase
# 
# This action uses the devsecops-hooks Docker container to perform security scanning
# for exposed secrets, credentials, and tokens within the repository.
#
# Inputs:
#   token: (required) GitHub repository token with the following permissions:
#     - read/write: contents, pull requests, issues
#     - read-only: security events
#
# Usage:
#   - uses: ministryofjustice/devsecops-actions/sca/steps/Secrets@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Notes:
#   - Runs in a Docker container using ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0
#   - Scans the current working directory mounted at /src
#   - GIT_MODE is disabled (set to false) for scanning

name: 🔑 Secrets
description: Secrets, credentials, tokens scan
author: Ministry of Justice UK

inputs:
  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Scan
      shell: bash
      run: docker run --rm
        \-e GIT_MODE=false
        \-v "$(pwd)":/src
        \ghcr.io/ministryofjustice/devsecops-hooks:v1.3.0 # https://github.com/ministryofjustice/devsecops-hooks
