# OpenSSF Scorecard Security Scanner Action
#
# This composite action runs the OpenSSF Scorecard security health metrics check
# on a repository to assess its security posture.
#
# Overview:
#   - Downloads and installs the OpenSSF Scorecard CLI tool (v5.4.0)
#   - Executes a local scan of the repository
#   - Generates a detailed JSON report with security metrics
#   - Displays results in the GitHub Actions step summary
#
# Inputs:
#   token: (required)
#     GitHub repository token with the following permissions:
#     - contents: read/write
#     - pull_request: read/write
#     - issues: read/write
#     - security_events: read-only
#
# Outputs:
#   - Creates a sca-scorecard.json file with detailed scan results
#   - Publishes a formatted summary to GitHub Actions step summary including:
#     * Overall security score (0-10)
#     * Individual check scores in a table format
#
# Usage Example:
#   - uses: ministryofjustice/devsecops-actions/sca/steps/OpenSSF@main
#     with:
#       token: ${{ secrets.GITHUB_TOKEN }}
#
# Note:
#   This action requires sudo/root privileges to install the scorecard binary
#   to /usr/local/bin/. Ensure the workflow has appropriate permissions.

name: 🛡 OSSF
description: OSSF scan
author: Ministry of Justice UK

inputs:
  token:
    required: true
    description: "GitHub repostiroy token with read and write privileges to contents, pull request, issues and read only perimission to security events."

runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        curl -L https://github.com/ossf/scorecard/releases/download/v5.4.0/scorecard_5.4.0_linux_amd64.tar.gz | tar -xz
        mv scorecard /usr/local/bin/scorecard
        chmod +x /usr/local/bin/scorecard

    - name: Scan
      shell: bash
      run: scorecard --local=./ --show-details --show-annotations --format json --output=sca-scorecard.json

    - name: Display
      shell: bash
      run: |
        echo "## 🛡 OSSF " >> $GITHUB_STEP_SUMMARY
        echo "### Score" >> $GITHUB_STEP_SUMMARY
        echo "**$(jq '.score' sca-scorecard.json)** / 10" >> $GITHUB_STEP_SUMMARY
        echo "### Overview" >> $GITHUB_STEP_SUMMARY
        echo "|Scan|Score (/10)|" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|-----------|" >> $GITHUB_STEP_SUMMARY
        jq -r '.checks[] | "| \(.name) | \(.score) |"' sca-scorecard.json >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
